# Generated by Django 4.2.4 on 2024-01-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lensapi", "0005_alter_post_options_post_visitor_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
